Add-bookings Sprint 14
koalannette/java-shareit pull request #2
Opened 2023-08-18 22:06 UTC by koalannette

2023-08-19 10:36 UTC, z8q requested changes

2023-08-19 10:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
В аннотации data используется equals и hashcode, вероятно здесь они не будут нужны.
Тут можно посмотреть примеры, когда в сущностях переопределяется hashcode и equals:
https://thorben-janssen.com/ultimate-guide-to-implementing-equals-and-hashcode-with-hibernate/
Вот этот абзац:
As you can see, Java’s default equals() and hashCode() methods only produce the required result if the Hibernate Session ensures that there is only 1 Java object that represents a specific record in the database table. If you load your entities in multiple Sessions or if you work with detached entities, you need to override these methods. In all other cases, it’s better to rely on Java’s default implementation.

Вот тут еще есть примеры, чуть подробнее
https://jpa-buddy.com/blog/lombok-and-jpa-what-may-go-wrong/

2023-08-19 10:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    Boolean existsByOwner_Id(Long ownerId);
Если не будем использовать, то стоит убрать

2023-08-19 10:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto createUser(@Validated(Create.class) @RequestBody UserDto userDto) {
При попытке повторно сохранить пользователя приходит:
```
{
	"error": "could not execute statement; SQL [n/a]; constraint
 [\"PUBLIC.UK_6DOTKOTT2KJSP8VW4D0M25FB7_INDEX_4 ON 
PUBLIC.USERS(EMAIL NULLS FIRST) VALUES 
( /* 1 */ 'bob@yandex.ru' )\"; SQL statement:\ninsert into users 
(user_id, email, name) values (default, ?, ?) [23505-214]]; 
nested exception is org.hibernate.exception.ConstraintViolationException: 
could not execute statement"
}
```
 Можно было бы присылать ошибку с сообщением `пользователь уже существует`

2023-08-19 10:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.NOT_FOUND,
Тут устанавливаем статус 404, но возвращается 500. Стоит перехватить через exception handler и там проставить статус

2023-08-19 10:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDtoResponse> getItemsByUserId(@RequestHeader(REQUEST_HEADER) Long id) {
По тз на этом запросе предполагается вывод в ответе даты последнего и ближайшего следующего бронирования для каждой вещи, но ответ приходит без дат:
```JSON
[
	{
		"id": 1,
		"name": "car",
		"description": "Tesla",
		"available": true,
		"lastBooking": {
			"id": 1,
			"bookerId": 3
		},
		"nextBooking": null,
		"comments": null
	}
]
```

2023-08-19 10:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDtoResponse> getItemsByUserId(@RequestHeader(REQUEST_HEADER) Long id) {
По тз отзывы можно будет увидеть по двум эндпоинтам — по `GET /items/{itemId}` для одной конкретной вещи и по `GET /items` для всех вещей данного пользователя.
`GET /items/{itemId}` выполнен корректно, отзыв отображается.
`GET /items` отзыв не отображается

2023-08-19 10:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/comment/dto/CommentDto.java
> +    private LocalDateTime created;
для полей с датами можно задать конкретный формат с использованием аннотации `@JsonFormat`

2023-08-19 10:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        User user = checkUserExistAndGet(ownerId);
если переменную user не используем, можно не создавать, 
оставить только вызов checkUserExistAndGet(ownerId)

2023-08-19 10:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        // log.info("Бронирование веши {} создано. Ожидает изменение статуса со стороны владельца.", item);
Закомментированные блоки лучше убирать

2023-08-19 10:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDtoResponse getBooking(@RequestHeader("X-Sharer-User-Id") long userId,
Выше в методах используется константа REQUEST_HEADER вместо "X-Sharer-User-Id".
И примитив long можно заменить на класс-обертку Long. Сейчас правда это ни на что не влияет, но если бы мы на хэдере поставили required = false и попробовали отправить null хэдер, программа бы ругалась, что примитив не может быть null

2023-08-19 10:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByItemIdInAndStartIsBeforeAndEndIsAfterOrderByStartDesc(
В целом, можно использовать, но когда имена методов становятся слишком длинные, стоит выделять запросы. Можно в `@Query()` над методом

2023-08-19 17:50 UTC, koalannette commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto createUser(@Validated(Create.class) @RequestBody UserDto userDto) {
Кирилл, Привет!
Я попробовала сделать проверку на уровне сервиса:
```
 @Transactional
    @Override
    public UserDto createUser(UserDto userDto) {
        if (!userRepository.existsUserByEmail(userDto.getEmail())) {
            User user = userRepository.save(UserMapper.toUser(userDto));
            return UserMapper.toUserDto(user);
        } else {
           throw new UserExistsAlreadyException("Пользователь уже существует");
        }
    }
```
Но так валятся последующие тесты.  Тесты в постмане ждут, что успешно создастся пользователь с ID = 1, а потом с ID = 3. Второго в тестах нет. 

Велось обсуждение насчёт этого случая и наставник сказал, что они ждут, что на поле email будет наложен unique constraint. И тогда база не вставит строку, но сделает инкремент id.

Т.е. если на уровне сервиса есть проверка на уникальность почты, то до репо не дойдет этот запрос, счётчик не увеличится как этого ожидают тесты.

2023-08-20 11:30 UTC, z8q approved these changes

2023-08-21 00:40 UTC, merged